SELECT
	*
FROM PG_NationalRates_APP_Fwrk_Timely NR
WHERE
	NR.PG_ExpEndYrID = '17/18'
	AND NR.PG_CollegeTypeID = 0
	AND NR.PG_WBLFundAgeGroupID IS NULL
	AND NR.PG_SSA1ID IS NULL
	--AND NR.PG_SSA2ID IS NULL
	AND NR.PG_ProgTypeID IS NULL
	AND NR.PG_FrameworkID IS NULL
	AND NR.PG_AppStandardID IS NULL

SELECT
	*
FROM PG_NationalRates_APP_Fwrk_Overall NR
WHERE
	NR.WB_HybridEndYearID = '17/18'
	AND NR.PG_CollegeTypeID = 0
	AND NR.PG_WBLFundAgeGroupID IS NULL
	AND NR.PG_SSA1ID IS NULL
	--AND NR.PG_SSA2ID IS NULL
	AND NR.PG_ProgTypeID IS NULL
	AND NR.PG_FrameworkID IS NULL
	AND NR.PG_AppStandardID IS NULL

SELECT *
FROM PG_NationalRates_APP_Demo_Overall NR_AGEGEN
WHERE
	NR_AGEGEN.WB_HybridEndYearID = '17/18'
	AND NR_AGEGEN.PG_CollegeTypeID = 0
	AND NR_AGEGEN.PG_WBLFundAgeGroupID IS NULL
	--AND NR_AGEGEN.PG_SSA1ID IS NULL
	AND NR_AGEGEN.PG_SSA2ID IS NULL
	AND NR_AGEGEN.PG_ProgTypeID IS NULL
	AND NR_AGEGEN.PG_EthnicityID IS NULL
	AND NR_AGEGEN.PG_EthnicityGroupQARID IS NULL
	AND NR_AGEGEN.PG_SexID IS NULL
	AND NR_AGEGEN.PG_DifficultyorDisabilityID IS NULL
	AND NR_AGEGEN.PG_LearningDifficultyID IS NULL